# Generated by Django 5.2.12 on 2026-03-28 01:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=2, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('moneda', models.CharField(default='USD', max_length=3)),
                ('num_tributario_label', models.CharField(default='NIT', max_length=20)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'países',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('tipo', models.CharField(choices=[('candidato', 'Candidato'), ('empresa', 'Empresa')], max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('ciudad', models.CharField(max_length=100)),
                ('cargo_actual', models.CharField(max_length=200)),
                ('años_experiencia', models.PositiveSmallIntegerField(default=0)),
                ('resumen', models.TextField(blank=True)),
                ('habilidades', models.JSONField(default=list)),
                ('disponibilidad', models.CharField(choices=[('inmediata', 'Disponible ahora'), ('1_mes', 'En 1 mes'), ('freelance', 'Solo freelance')], default='inmediata', max_length=20)),
                ('modalidad', models.CharField(choices=[('presencial', 'Presencial'), ('remoto', 'Remoto'), ('hibrido', 'Híbrido')], default='hibrido', max_length=20)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos/')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de revisión'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=15)),
                ('nota_rechazo', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='candidato', to=settings.AUTH_USER_MODEL)),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='talent_app.pais')),
                ('sectores', models.ManyToManyField(blank=True, to='talent_app.sector')),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='Educacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('institucion', models.CharField(max_length=200)),
                ('año_fin', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educaciones', to='talent_app.candidato')),
            ],
            options={
                'ordering': ['orden', '-año_fin'],
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('num_tributario', models.CharField(max_length=50)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de verificación'), ('activa', 'Activa'), ('bloqueada', 'Bloqueada')], default='pendiente', max_length=15)),
                ('stripe_customer_id', models.CharField(blank=True, max_length=100)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='empresa', to=settings.AUTH_USER_MODEL)),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='talent_app.pais')),
            ],
        ),
        migrations.CreateModel(
            name='ExperienciaLaboral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=200)),
                ('cargo', models.CharField(max_length=200)),
                ('año_inicio', models.PositiveSmallIntegerField()),
                ('año_fin', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiencias', to='talent_app.candidato')),
            ],
            options={
                'ordering': ['orden', '-año_inicio'],
            },
        ),
        migrations.CreateModel(
            name='IdiomaCandiato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idioma', models.CharField(max_length=50)),
                ('nivel', models.CharField(choices=[('nativo', 'Nativo'), ('avanzado', 'Avanzado (C1–C2)'), ('intermedio', 'Intermedio (B1–B2)'), ('basico', 'Básico (A1–A2)')], max_length=15)),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idiomas', to='talent_app.candidato')),
            ],
        ),
        migrations.CreateModel(
            name='DescargaCV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_payment_id', models.CharField(blank=True, max_length=200)),
                ('stripe_session_id', models.CharField(blank=True, max_length=200)),
                ('monto_usd', models.DecimalField(decimal_places=2, default=5.0, max_digits=8)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de pago'), ('pagado', 'Pagado'), ('fallido', 'Fallido')], default='pendiente', max_length=15)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('pagado_en', models.DateTimeField(blank=True, null=True)),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='descargas', to='talent_app.candidato')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='descargas', to='talent_app.empresa')),
            ],
            options={
                'ordering': ['-creado_en'],
                'unique_together': {('empresa', 'candidato')},
            },
        ),
    ]
